package main.java.models;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.Objects;

/**
 * Person Model for REST API
 */
@Entity
@JsonAutoDetect(fieldVisibility = JsonAutoDetect.Visibility.NONE, getterVisibility = JsonAutoDetect.Visibility.NONE) 
public class Person {

	/**
	 * Unique ID used to identify an individual Person
	 * Allowed to be null so that it passes validation as IDs are generated by the database
	 */
	@Id
	@Column(name="id", nullable=false, updatable=false)
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private Long id;
	
	/**
	 * Person first name
	 */
	@Column(name="firstName", nullable=false)
	@NotNull
	@Size(max=20)
	private String firstName;

	/**
	 * Person last name
	 */
	@Column(name="lastName", nullable=false)
	@NotNull
	@Size(max=20)
	private String lastName;
	
	/**
	 * JPA needs this to deserialize objects 
	 */
	Person(){
		
	}
		
	/**
	 * Simple constructor for Person object
	 * @param id Person's unique ID
	 * @param firstName Person's first name
	 * @param lastName Person's last name
	 */
	public Person( Long id, String firstName, String lastName)
	{
		this.id = id;
		
		this.firstName = firstName;
		
		this.lastName = lastName;
	}
	
	/**
	 * ID Setter
	 * @param id The value to set this Person's Id to
	 */
	public void setId(Long id){
		this.id = id;
	}
	
	/**
	 * ID Getter
	 * @return This Person's Id
	 */
	@JsonProperty("id")
	public Long getId() {
		return id;
	}
	
	/**
	 * First Name Getter
	 * @return This Person's first name
	 */
	@JsonProperty("firstName")
	public String getFirstName() {
		return firstName;
	}
	
	/**
	 * Last Name getter
	 * @return This Person's last name
	 */
	@JsonProperty("lastName")
	public String getLastName() {
		return lastName;
	}
	
}
